### ISSUE TITLE
error in NHANES 2017 2018 Process.R  when executing mutate(subset = 1:n())

### ISSUE THREAD

**Issue by linchundan88** [rwnahhas/RMPH_Resources#1]
When executing the line 680 "mutate(subset = 1:n())", the program raised an error.

**Comment by rwnahhas** [comment]
Thank you for the notification. This issue has been resolved. The issue was due to nhanesA() now reading variables in as factors, breaking the later code and resulting in errors. The updated code now works, however the resulting datasets no longer have labels.
